# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f1a67abc6bbfd10f9b09548ad22a6632126c9a9000d4e90b21b1dd087ab1e98a4188f1e310ec17fd12580d56f294c73bb4602b1ec13b903e4cfd92496ec31a5

test:
  secret_key_base: a57bc0f92f21ec735f027b5bea83cf032d6c52adb8eb0d7deebecb5ad5b032fd10e46fd8fdd1d0b65625498a22930ad8d5dce1e38e7a623ffa85b6b41f41e302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
