# myapp.rb
require 'sinatra'

get '/' do
  'Cupcake ipsum dolor sit amet croissant chupa chups caramels. I love liquorice gummi bears gingerbread. Cake I love topping tootsie roll sweet roll pudding carrot cake. I love chupa chups halvah oat cake gummies soufflé I love pudding. Dragée chocolate cake I love. Jelly-o liquorice liquorice topping fruitcake cotton candy cookie icing. Gingerbread wafer pie apple pie chocolate topping danish tootsie roll. Jelly oat cake cake gummies marzipan cotton candy dragée oat cake chocolate. Chocolate brownie candy canes tart I love cake danish. Marshmallow tart I love chocolate bar cheesecake lemon drops tart I love. Gingerbread cheesecake I love donut. Jelly chocolate carrot cake jelly-o bonbon caramels chocolate cake sweet roll.
I love cake gingerbread tootsie roll. Dessert muffin carrot cake marzipan apple pie chupa chups halvah liquorice. Marzipan sweet marshmallow apple pie cheesecake fruitcake tart I love biscuit. Liquorice oat cake candy macaroon bonbon I love chocolate cake cookie marshmallow. Pie gummies toffee danish. Gummi bears cake brownie icing pie halvah. Jelly beans jelly bear claw apple pie. Danish apple pie donut sweet. I love danish cookie powder chocolate bar macaroon gummi bears powder. I love icing marshmallow tart. I love gingerbread cheesecake muffin tiramisu cake cotton candy donut halvah. Tiramisu oat cake biscuit liquorice tootsie roll powder dragée I love cake. Cake pudding I love sugar plum.
Tiramisu gingerbread icing I love pudding sweet roll chocolate bar gingerbread. Donut bear claw halvah jelly beans candy bear claw. Liquorice I love powder powder topping cupcake. I love marzipan macaroon chocolate I love tootsie roll. Chocolate pastry caramels croissant toffee. Ice cream I love ice cream bonbon donut candy canes gingerbread oat cake chocolate cake. Chupa chups pie chupa chups cookie pastry lollipop topping marzipan tootsie roll. Powder pastry oat cake. Cake lemon drops sugar plum cotton candy cotton candy jujubes tart lollipop croissant. Bonbon wafer pudding. Marzipan I love sweet roll. Toffee dessert marzipan chocolate bar tiramisu fruitcake.
Caramels apple pie cotton candy wafer. Caramels gummies brownie cupcake jelly beans. Tootsie roll gingerbread jujubes candy canes. Cake chupa chups dragée biscuit sweet bonbon. Powder apple pie I love I love icing powder croissant. Biscuit I love jujubes sugar plum powder marzipan I love. Bear claw cookie topping toffee donut gummies candy soufflé oat cake. Ice cream chupa chups jujubes chocolate bar liquorice jelly-o chupa chups. Lemon drops bonbon apple pie tiramisu halvah muffin. Brownie brownie I love carrot cake lollipop. Carrot cake dragée lollipop I love brownie I love liquorice gummi bears. Ice cream oat cake powder candy. Cake bear claw marshmallow soufflé gummi bears I love fruitcake chupa chups liquorice. Cake croissant apple pie tootsie roll powder.
Bear claw macaroon topping I love donut icing tiramisu. Ice cream cookie jelly beans sesame snaps toffee candy canes tart. Chupa chups cheesecake tart I love. Pastry ice cream I love tiramisu biscuit danish. Chocolate cake dragée icing. Sesame snaps marshmallow macaroon croissant donut dragée liquorice fruitcake croissant. Sweet macaroon gingerbread caramels pudding. Pastry chocolate cake chupa chups biscuit candy halvah apple pie lollipop. Cake topping chocolate bar I love sugar plum candy canes I love. Macaroon jelly beans I love toffee. Halvah I love lemon drops chocolate marshmallow I love. I love pastry gummies brownie. Sweet croissant pastry apple pie cotton candy cupcake biscuit chupa chups topping. Cookie cake wafer sugar plum. !'
end